---
abstract: 'Return difference between to hashes as a hash'
author:
  - 'Bjorn-Olav Strand <bo@startsiden.no>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.92'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hash-Diff
no_index:
  directory:
    - inc
    - t
requires:
  Hash::Merge: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.002
